// Generated by `opennextjs-cloudflare build` before Wrangler bundles this file.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module is intentionally absent before build.
import openNextWorker from "./.open-next/worker.js";

type MemberWorkerEnvironment = Record<string, unknown> & {
  FEATURE_AUTH?: string;
  FEATURE_CONTENT?: string;
  FEATURE_PAYMENTS?: string;
  MEMBER_APP_URL?: string;
  RESEND_API_KEY?: string;
  RESEND_FROM?: string;
  WORKER_INTERNAL_SECRET?: string;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

const responseHeaders = {
  "Permissions-Policy": "camera=(), geolocation=(), microphone=()",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Strict-Transport-Security": "max-age=31536000",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
} as const;

function enabled(value: string | undefined) {
  return value === "true";
}

async function invokeInternalRoute(
  path: string,
  environment: MemberWorkerEnvironment,
  context: WorkerContext,
) {
  if (!environment.WORKER_INTERNAL_SECRET) {
    throw new Error("worker_internal_secret_missing");
  }
  const response = await openNextWorker.fetch(
    new Request(`https://member-worker.internal${path}`, {
      headers: {
        Authorization: `Bearer ${environment.WORKER_INTERNAL_SECRET}`,
      },
      method: "POST",
    }),
    environment,
    context,
  );
  if (!response.ok) {
    await response.body?.cancel();
    throw new Error(`scheduled_route_failed:${path}:${response.status}`);
  }
  await response.body?.cancel();
}

async function runScheduledOutboxes(
  environment: MemberWorkerEnvironment,
  context: WorkerContext,
) {
  const routes: string[] = [];
  if (enabled(environment.FEATURE_CONTENT)) {
    routes.push("/api/internal/outbox/content-watermarks");
  }
  if (enabled(environment.FEATURE_PAYMENTS)) {
    routes.push("/api/internal/outbox/payments");
  }
  if (
    enabled(environment.FEATURE_AUTH) &&
    environment.RESEND_API_KEY &&
    environment.RESEND_FROM &&
    environment.MEMBER_APP_URL
  ) {
    routes.push("/api/internal/outbox/invitations");
  }

  const results = await Promise.allSettled(
    routes.map((path) => invokeInternalRoute(path, environment, context)),
  );
  const failures = results.filter(
    (result): result is PromiseRejectedResult => result.status === "rejected",
  );
  if (failures.length > 0) {
    const codes = failures.map((failure) =>
      failure.reason instanceof Error
        ? failure.reason.message
        : "unknown_scheduled_failure",
    );
    throw new Error(codes.join(","));
  }
}

const worker = {
  async fetch(
    request: Request,
    environment: MemberWorkerEnvironment,
    context: WorkerContext,
  ) {
    const requestUrl = new URL(request.url);
    const forwardedProtocol = request.headers.get("x-forwarded-proto");
    if (
      requestUrl.protocol === "http:" ||
      forwardedProtocol?.toLowerCase() === "http"
    ) {
      requestUrl.protocol = "https:";
      return new Response(null, {
        headers: { ...responseHeaders, Location: requestUrl.toString() },
        status: 308,
      });
    }

    const response = await openNextWorker.fetch(
      request,
      environment,
      context,
    );
    const headers = new Headers(response.headers);
    for (const [name, value] of Object.entries(responseHeaders)) {
      headers.set(name, value);
    }
    return new Response(response.body, {
      headers,
      status: response.status,
      statusText: response.statusText,
    });
  },

  async scheduled(
    _controller: unknown,
    environment: MemberWorkerEnvironment,
    context: WorkerContext,
  ) {
    context.waitUntil(runScheduledOutboxes(environment, context));
  },
};

export default worker;

// Required by OpenNext when cache Durable Objects are enabled.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module is intentionally absent before build.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
