// Generated by `opennextjs-cloudflare build` before Wrangler bundles this file.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module is intentionally absent before build.
import openNextWorker from "./.open-next/worker.js";

type MemberWorkerEnvironment = Record<string, unknown> & {
  MEMBER_APP_MODE?: string;
  FEATURE_AUTH?: string;
  FEATURE_CONTENT?: string;
  FEATURE_PAYMENTS?: string;
  MEMBER_APP_URL?: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  NEXT_PUBLIC_SUPABASE_URL?: string;
  RESEND_API_KEY?: string;
  RESEND_FROM?: string;
  SUPABASE_SECRET_KEY?: string;
  WORKER_INTERNAL_SECRET?: string;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

const responseHeaders = {
  "Permissions-Policy": "camera=(), geolocation=(), microphone=()",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Strict-Transport-Security": "max-age=31536000",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
} as const;

function contentSecurityPolicy(environment: MemberWorkerEnvironment) {
  const connectSources = ["'self'"];
  if (environment.NEXT_PUBLIC_SUPABASE_URL) {
    try {
      const supabaseUrl = new URL(environment.NEXT_PUBLIC_SUPABASE_URL);
      connectSources.push(supabaseUrl.origin);
      if (supabaseUrl.protocol === "https:") {
        connectSources.push(`wss://${supabaseUrl.host}`);
      }
    } catch {
      // Environment validation returns 503 before the application is invoked.
    }
  }
  return [
    "base-uri 'self'",
    `connect-src ${connectSources.join(" ")}`,
    "default-src 'self'",
    "font-src 'self' data:",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "img-src 'self' data: blob: https:",
    "object-src 'none'",
    "script-src 'self' 'unsafe-inline'",
    "style-src 'self' 'unsafe-inline'",
    "upgrade-insecure-requests",
  ].join("; ");
}

function hardenedHeaders(environment: MemberWorkerEnvironment) {
  return {
    ...responseHeaders,
    "Content-Security-Policy": contentSecurityPolicy(environment),
  };
}

function enabled(value: string | undefined) {
  return value === "true";
}

function productionConfigurationReady(
  environment: MemberWorkerEnvironment,
) {
  if (environment.MEMBER_APP_MODE !== "production") return true;
  return Boolean(
    enabled(environment.FEATURE_AUTH) &&
      enabled(environment.FEATURE_CONTENT) &&
      environment.NEXT_PUBLIC_SUPABASE_URL &&
      environment.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY &&
      environment.SUPABASE_SECRET_KEY,
  );
}

function requestId(request: Request) {
  return request.headers.get("cf-ray") ?? crypto.randomUUID();
}

async function invokeInternalRoute(
  path: string,
  environment: MemberWorkerEnvironment,
  context: WorkerContext,
) {
  if (!environment.WORKER_INTERNAL_SECRET) {
    throw new Error("worker_internal_secret_missing");
  }
  const response = await openNextWorker.fetch(
    new Request(`https://member-worker.internal${path}`, {
      headers: {
        Authorization: `Bearer ${environment.WORKER_INTERNAL_SECRET}`,
      },
      method: "POST",
    }),
    environment,
    context,
  );
  if (!response.ok) {
    await response.body?.cancel();
    throw new Error(`scheduled_route_failed:${path}:${response.status}`);
  }
  await response.body?.cancel();
}

async function runScheduledOutboxes(
  environment: MemberWorkerEnvironment,
  context: WorkerContext,
) {
  const routes: string[] = [];
  if (enabled(environment.FEATURE_CONTENT)) {
    routes.push("/api/internal/outbox/content-watermarks");
  }
  if (enabled(environment.FEATURE_PAYMENTS)) {
    routes.push("/api/internal/outbox/payments");
  }
  if (
    enabled(environment.FEATURE_AUTH) &&
    environment.RESEND_API_KEY &&
    environment.RESEND_FROM &&
    environment.MEMBER_APP_URL
  ) {
    routes.push("/api/internal/outbox/invitations");
  }

  const results = await Promise.allSettled(
    routes.map((path) => invokeInternalRoute(path, environment, context)),
  );
  const failures = results.filter(
    (result): result is PromiseRejectedResult => result.status === "rejected",
  );
  if (failures.length > 0) {
    const codes = failures.map((failure) =>
      failure.reason instanceof Error
        ? failure.reason.message
        : "unknown_scheduled_failure",
    );
    throw new Error(codes.join(","));
  }
}

const worker = {
  async fetch(
    request: Request,
    environment: MemberWorkerEnvironment,
    context: WorkerContext,
  ) {
    const requestUrl = new URL(request.url);
    const currentRequestId = requestId(request);
    if (requestUrl.pathname === "/healthz") {
      const ready = productionConfigurationReady(environment);
      return new Response(
        JSON.stringify({
          mode: environment.MEMBER_APP_MODE ?? "preview",
          status: ready ? "ready" : "not_ready",
        }),
        {
          headers: {
            ...hardenedHeaders(environment),
            "Content-Type": "application/json; charset=utf-8",
            "X-Request-Id": currentRequestId,
          },
          status: ready ? 200 : 503,
        },
      );
    }
    if (!productionConfigurationReady(environment)) {
      return new Response(
        JSON.stringify({ code: "member_app_not_configured" }),
        {
          headers: {
            ...hardenedHeaders(environment),
            "Content-Type": "application/json; charset=utf-8",
            "X-Request-Id": currentRequestId,
          },
          status: 503,
        },
      );
    }
    const forwardedProtocol = request.headers.get("x-forwarded-proto");
    if (
      requestUrl.protocol === "http:" ||
      forwardedProtocol?.toLowerCase() === "http"
    ) {
      requestUrl.protocol = "https:";
      return new Response(null, {
        headers: {
          ...hardenedHeaders(environment),
          Location: requestUrl.toString(),
          "X-Request-Id": currentRequestId,
        },
        status: 308,
      });
    }

    const response = await openNextWorker.fetch(
      request,
      environment,
      context,
    );
    const headers = new Headers(response.headers);
    for (const [name, value] of Object.entries(hardenedHeaders(environment))) {
      headers.set(name, value);
    }
    headers.set("X-Request-Id", currentRequestId);
    return new Response(response.body, {
      headers,
      status: response.status,
      statusText: response.statusText,
    });
  },

  async scheduled(
    _controller: unknown,
    environment: MemberWorkerEnvironment,
    context: WorkerContext,
  ) {
    context.waitUntil(runScheduledOutboxes(environment, context));
  },
};

export default worker;

// Required by OpenNext when cache Durable Objects are enabled.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module is intentionally absent before build.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
