// Generated by `opennextjs-cloudflare build` before Wrangler bundles this file.
// @ts-expect-error The generated module is intentionally absent before build.
import openNextWorker from "./.open-next/worker.js";

const responseHeaders = {
  "Permissions-Policy": "camera=(), geolocation=(), microphone=()",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Strict-Transport-Security": "max-age=31536000",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
} as const;

const worker = {
  async fetch(request: Request, environment: unknown, context: unknown) {
    const requestUrl = new URL(request.url);
    const forwardedProtocol = request.headers.get("x-forwarded-proto");

    if (
      requestUrl.protocol === "http:" ||
      forwardedProtocol?.toLowerCase() === "http"
    ) {
      requestUrl.protocol = "https:";

      return new Response(null, {
        headers: {
          ...responseHeaders,
          Location: requestUrl.toString(),
        },
        status: 308,
      });
    }

    const response = await openNextWorker.fetch(
      request,
      environment,
      context,
    );
    const headers = new Headers(response.headers);

    for (const [name, value] of Object.entries(responseHeaders)) {
      headers.set(name, value);
    }

    return new Response(response.body, {
      headers,
      status: response.status,
      statusText: response.statusText,
    });
  },
};

export default worker;
